name: jos
favicon: null
layout_spectrum: 0.16459196666255593
typography_spectrum: 0.5541876668576151
title: Jos on the grid and off the record
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9820780192967504
  lightness: 0.8911957880482078
  saturation: 0.418224559398368
  rhythmicContrast: 0.6236013530287892
purpose: []
